### ISSUE TITLE
KeyError: "There is no item named 'xl/_rels/workbook.bin.rels' in the archive"

### ISSUE THREAD

**Issue by akashTR20075** [wwwiiilll/pyxlsb#53]
I've had pyxlsb working before, but now i seem to be getting this error. Do you think this is an installation issue, file issue or a bug? 
details of installation: 
- python: 3.12.4 
- Pandas: 2.2.3
- pyxlsb: 1.0.10

what i'm trying: 
```
df = pd.read_excel(
'./G-L 1 Exhibits 2Q 2024 PUBL.xlsx', 
sheet_name = 'RCoup',
engine='pyxlsb'
)
```

Full stack Trace: 

```
Traceback (most recent call last):
  File "C:\Users\tr20075\Work\temp tests\test.py", line 6, in <module>
    df = pd.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pandas\io\excel\_pyxlsb.py", line 46, in __init__
    super().__init__(
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pandas\io\excel\_base.py", line 573, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pandas\io\excel\_pyxlsb.py", line 67, in load_workbook
    return open_workbook(filepath_or_buffer, **engine_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pyxlsb\__init__.py", line 11, in open_workbook
    return Workbook(fp=zf, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pyxlsb\workbook.py", line 20, in __init__
    self._parse()
  File "C:\Users\tr20075\AppData\Local\pypoetry\Cache\virtualenvs\temp_tests-n_Qx-M3z-py3.12\Lib\site-packages\pyxlsb\workbook.py", line 34, in _parse
    with self._zf.open('xl/_rels/workbook.bin.rels', 'r') as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\.pyenv\pyenv-win\versions\3.12.4\Lib\zipfile\__init__.py", line 1604, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tr20075\.pyenv\pyenv-win\versions\3.12.4\Lib\zipfile\__init__.py", line 1532, in getinfo
    raise KeyError(
KeyError: "There is no item named 'xl/_rels/workbook.bin.rels' in the archive"
```

**Comment by akashTR20075** [comment]
ok i'm dumb apparently. I didn't realise my excel was not a binary (xlsb), it was a regular xlsx file *facepalm*. 
Sorry if i wasted anyone's time.
